services:

  # DNS Resolver (Required)
  dnsmasq:
    image: 4km3/dnsmasq:2.85-r2
    container_name: anydev-dnsmasq
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    command:
      - "--log-facility=-"
      - "--server=8.8.8.8"
      - "--address=/.site.local/127.0.0.1"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - anydev

  # Reverse Proxy (required)
  traefik:
    image: traefik:v2.9
    container_name: anydev-traefik
    restart: unless-stopped
    command:
      - "--configFile=/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOME}/.anydev/certs:/certs:ro
      - ./traefik.yml:/traefik.yml:ro
    networks:
      - anydev

  # ===========================================
  # Profile-Specific Services
  # ===========================================

  # Databases
  mysql:
    image: mysql:8
    container_name: anydev-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${HOME}/.anydev/mysql:/var/lib/mysql
    networks:
      - anydev
    profiles:
      - lamp
      - mysql

  mongo:
    image: mongo:latest
    container_name: anydev-mongo
    restart: unless-stopped
    volumes:
      - ${HOME}/.anydev/mongodb:/data/db
    networks:
      - anydev
    profiles:
      - mongo

# Caches
  redis:
    image: redis:latest
    container_name: anydev-redis
    restart: unless-stopped
    networks:
      - anydev
    profiles:
      - redis

  memcached:
    image: memcached:latest
    container_name: anydev-memcached
    restart: unless-stopped
    networks:
      - anydev
    profiles:
      - memcached

networks:
  anydev:
    name: anydev
    driver: bridge

volumes:
  mysql_data:
