services:

  # DNS Resolver (Required)
  dnsmasq:
    image: 4km3/dnsmasq:2.85-r2
    container_name: anydev-dnsmasq
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    command:
      - "--log-debug"
      - "--log-facility=-"
      - "--server=8.8.8.8" # Use Google DNS by default
      - "--server=8.8.4.4" # Use Google DNS by default
      - "--address=/site.test/127.0.0.1"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - anydev

  # Reverse Proxy (required)
  traefik:
    image: traefik:v2.9
    container_name: anydev-traefik
    restart: unless-stopped
    command:
      - "--configFile=/traefik.static.yml"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOME}/.anydev/certs:/certs:ro
      - ./services/traefik.static.yml:/traefik.static.yml:ro
      - ./services/traefik.dynamic.yml:/traefik.dynamic.yml:ro
    networks:
      - anydev

  # ===========================================
  # Profile-Specific Services
  # ===========================================

  # SMTP/Email Catching Service - MailPit
  smtp:
    image: axllent/mailpit
    container_name: anydev-smtp
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: smtp.site.test
      MP_SMTP_BIND_ADDR: 0.0.0.0:25
      MP_UI_BIND_ADDR: 0.0.0.0:80
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    expose:
      - "80"
      - "25"
    networks:
      - anydev
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.mailhog.loadbalancer.server.port=80"
      - "traefik.http.routers.php-mail.rule=Host(`smtp.site.test`)"
      - "traefik.http.routers.php-mail.entrypoints=web"  # HTTP entry point
      - "traefik.http.routers.php-mail-secure.rule=Host(`smtp.site.test`)"  # HTTPS entry point
      - "traefik.http.routers.php-mail-secure.entrypoints=websecure"
      - "traefik.http.routers.php-mail-secure.tls=true"
      - type=email
      - type=smtp

  # Databases
  mysql:
    image: mysql:${VER_MYSQL}
    container_name: anydev-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${HOME}/.anydev/mysql-${VER_MYSQL}:/var/lib/mysql
    networks:
      - anydev
    ports:
      - "3306:3306"
    labels:
      - type=db
      - type=relational-db
    profiles:
      - mysql

  postgres:
    image: postgres:${VER_POSTGRES}
    container_name: anydev-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${HOME}/.anydev/postgresql-${POSTGRES_PASSWORD}:/var/lib/postgresql/data
    networks:
      - anydev
    ports:
      - "5432:5432"
    labels:
      - type=db
      - type=relational-db
    profiles:
      - postgres

  mongo:
    image: mongo:${VER_MONGO}
    container_name: anydev-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - ${HOME}/.anydev/mongodb-${VER_MONGO}:/data/db
    networks:
      - anydev
    ports:
      # For management on host machine
      - "27017:27017"
    labels:
      - type=db
      - type=nosql
    profiles:
      - mongo

# Caches
  redis:
    image: redis:${VER_REDIS}
    container_name: anydev-redis
    restart: unless-stopped
    networks:
      - anydev
    labels:
      - type=caching
      - type=kvs
    profiles:
      - redis

  memcached:
    image: memcached:${VER_MEMCACHED}
    container_name: anydev-memcached
    restart: unless-stopped
    networks:
      - anydev
    labels:
      - type=caching
      - type=kvs
    profiles:
      - memcached

# TODO: elasticsearch
# TODO: mariadb
# TODO: selenium (has separate official arm & x86 images)
# TODO: Prometheus, Grafana++?
# TODO: Kibana?
# TODO: rabbitmq?
# TODO: smtp/email catching?
# TODO: HC Vault?

networks:
  anydev:
    name: anydev
    driver: bridge
