entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

tls:
  certificates:
    - certFile: "/certs/_wildcard.site.test.pem"
      keyFile: "/certs/_wildcard.site.test-key.pem"