# ===============================
# Traefik static configuration
# -------------------------------
# i.e. initialization only
# ===============================

# Traefik will monitor these ports
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# Traefik needs to use Docker. Don't automatically expose containers.
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: anydev
  file:
    filename: "/traefik.dynamic.yml"
    watch: true

# More aggressive logging for local dev
log:
  level: DEBUG

# Allow unrestricted access to local Traefik dashboard
api:
  insecure: true
