# selenium-grid.yaml
# Default values for selenium
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  namespace: anydev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
        - name: selenium-hub
          image: selenium/hub:4.1.0
          ports:
            - containerPort: 4444
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  namespace: anydev
spec:
  type: NodePort
  selector:
    app: selenium-hub
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 4444
      nodePort: 4444  # Port to expose Selenium Hub on the host machine
