services:
  app:
    container_name: ${HOSTNAME}.site.test
    build:
      context: .
    volumes:
      - ./src:/var/www/html
      - ./server/conf.d:/etc/apache2/conf.d
      - ./server/php.ini:/usr/local/etc/php/php.ini
      - ./reports:/var/www/reports
    env_file:
      - .env
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - VIRTUAL_HOST=${HOSTNAME}.site.test
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php-${HOSTNAME}.rule=Host(`${HOSTNAME}.site.test`)"
      - "traefik.http.routers.php-${HOSTNAME}.entrypoints=web"  # HTTP entry point
      - "traefik.http.routers.php-${HOSTNAME}-secure.rule=Host(`${HOSTNAME}.site.test`)"  # HTTPS entry point
      - "traefik.http.routers.php-${HOSTNAME}-secure.entrypoints=websecure"  # Secure (i.e. HTTPS) entry point
      - "traefik.http.routers.php-${HOSTNAME}-secure.tls=true"
    expose:
      - "80"
    networks:
      - anydev

networks:
  anydev:
    name: anydev
    driver: bridge
    external: true